# Generated by Django 2.2.7 on 2019-12-03 17:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('project_slug', models.SlugField(max_length=500)),
                ('resource_id', models.CharField(editable=False, max_length=500)),
                ('content', djongo.models.fields.ListField(blank=True, default=[], null=True)),
                ('created_dt', models.DateTimeField(editable=False)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_dt'],
            },
        ),
    ]
